namespace MapleGriffin.CurrencyCodes
{
    public static class CurrencyCodeExtensions
    {
        public static IList<CountryCode> Countries(this CurrencyCode currencyCode)
        {
            return CountryCurrencyMapping.Map.Where(m => m.Value == currencyCode).Select(m => m.Key).ToList();
        }

        public static string Name(this CurrencyCode currencyCode)
        {
            return currencyCode switch
            {
                CurrencyCode.ALL => "Lek",
                CurrencyCode.DZD => "Algerian Dinar",
                CurrencyCode.ARS => "Argentine Peso",
                CurrencyCode.AUD => "Australian Dollar",
                CurrencyCode.BSD => "Bahamian Dollar",
                CurrencyCode.BHD => "Bahraini Dinar",
                CurrencyCode.BDT => "Taka",
                CurrencyCode.AMD => "Armenian Dram",
                CurrencyCode.BBD => "Barbados Dollar",
                CurrencyCode.BMD => "Bermudian Dollar",
                CurrencyCode.BTN => "Ngultrum",
                CurrencyCode.BOB => "Boliviano",
                CurrencyCode.BWP => "Pula",
                CurrencyCode.BZD => "Belize Dollar",
                CurrencyCode.SBD => "Solomon Islands Dollar",
                CurrencyCode.BND => "Brunei Dollar",
                CurrencyCode.MMK => "Kyat",
                CurrencyCode.BIF => "Burundi Franc",
                CurrencyCode.KHR => "Riel",
                CurrencyCode.CAD => "Canadian Dollar",
                CurrencyCode.CVE => "Cabo Verde Escudo",
                CurrencyCode.KYD => "Cayman Islands Dollar",
                CurrencyCode.LKR => "Sri Lanka Rupee",
                CurrencyCode.CLP => "Chilean Peso",
                CurrencyCode.CNY => "Yuan Renminbi",
                CurrencyCode.COP => "Colombian Peso",
                CurrencyCode.KMF => "Comoro Franc",
                CurrencyCode.CRC => "Costa Rican Colon",
                CurrencyCode.HRK => "Kuna",
                CurrencyCode.CUP => "Cuban Peso",
                CurrencyCode.CZK => "Czech Koruna",
                CurrencyCode.DKK => "Danish Krone",
                CurrencyCode.DOP => "Dominican Peso",
                CurrencyCode.SVC => "El Salvador Colon",
                CurrencyCode.ETB => "Ethiopian Birr",
                CurrencyCode.ERN => "Nakfa",
                CurrencyCode.FKP => "Falkland Islands Pound",
                CurrencyCode.FJD => "Fiji Dollar",
                CurrencyCode.DJF => "Djibouti Franc",
                CurrencyCode.GMD => "Dalasi",
                CurrencyCode.GIP => "Gibraltar Pound",
                CurrencyCode.GTQ => "Quetzal",
                CurrencyCode.GNF => "Guinea Franc",
                CurrencyCode.GYD => "Guyana Dollar",
                CurrencyCode.HTG => "Gourde",
                CurrencyCode.HNL => "Lempira",
                CurrencyCode.HKD => "Hong Kong Dollar",
                CurrencyCode.HUF => "Forint",
                CurrencyCode.ISK => "Iceland Krona",
                CurrencyCode.INR => "Indian Rupee",
                CurrencyCode.IDR => "Rupiah",
                CurrencyCode.IRR => "Iranian Rial",
                CurrencyCode.IQD => "Iraqi Dinar",
                CurrencyCode.ILS => "New Israeli Sheqel",
                CurrencyCode.JMD => "Jamaican Dollar",
                CurrencyCode.JPY => "Yen",
                CurrencyCode.KZT => "Tenge",
                CurrencyCode.JOD => "Jordanian Dinar",
                CurrencyCode.KES => "Kenyan Shilling",
                CurrencyCode.KPW => "North Korean Won",
                CurrencyCode.KRW => "Won",
                CurrencyCode.KWD => "Kuwaiti Dinar",
                CurrencyCode.KGS => "Som",
                CurrencyCode.LAK => "Kip",
                CurrencyCode.LBP => "Lebanese Pound",
                CurrencyCode.LSL => "Loti",
                CurrencyCode.LRD => "Liberian Dollar",
                CurrencyCode.LYD => "Libyan Dinar",
                CurrencyCode.MOP => "Pataca",
                CurrencyCode.MWK => "Kwacha",
                CurrencyCode.MYR => "Malaysian Ringgit",
                CurrencyCode.MVR => "Rufiyaa",
                CurrencyCode.MUR => "Mauritius Rupee",
                CurrencyCode.MXN => "Mexican Peso",
                CurrencyCode.MNT => "Tugrik",
                CurrencyCode.MDL => "Moldovan Leu",
                CurrencyCode.MAD => "Moroccan Dirham",
                CurrencyCode.OMR => "Rial Omani",
                CurrencyCode.NAD => "Namibia Dollar",
                CurrencyCode.NPR => "Nepalese Rupee",
                CurrencyCode.ANG => "Netherlands Antillean Guilder",
                CurrencyCode.AWG => "Aruban Florin",
                CurrencyCode.VUV => "Vatu",
                CurrencyCode.NZD => "New Zealand Dollar",
                CurrencyCode.NIO => "Cordoba Oro",
                CurrencyCode.NGN => "Naira",
                CurrencyCode.NOK => "Norwegian Krone",
                CurrencyCode.PKR => "Pakistan Rupee",
                CurrencyCode.PAB => "Balboa",
                CurrencyCode.PGK => "Kina",
                CurrencyCode.PYG => "Guarani",
                CurrencyCode.PEN => "Nuevo Sol",
                CurrencyCode.PHP => "Philippine Peso",
                CurrencyCode.QAR => "Qatari Rial",
                CurrencyCode.RUB => "Russian Ruble",
                CurrencyCode.RWF => "Rwanda Franc",
                CurrencyCode.SHP => "Saint Helena Pound",
                CurrencyCode.SAR => "Saudi Riyal",
                CurrencyCode.SCR => "Seychelles Rupee",
                CurrencyCode.SGD => "Singapore Dollar",
                CurrencyCode.VND => "Dong",
                CurrencyCode.SOS => "Somali Shilling",
                CurrencyCode.ZAR => "Rand",
                CurrencyCode.SSP => "South Sudanese Pound",
                CurrencyCode.SZL => "Lilangeni",
                CurrencyCode.SEK => "Swedish Krona",
                CurrencyCode.CHF => "Swiss Franc",
                CurrencyCode.SYP => "Syrian Pound",
                CurrencyCode.THB => "Baht",
                CurrencyCode.TOP => "Pa’anga",
                CurrencyCode.TTD => "Trinidad and Tobago Dollar",
                CurrencyCode.AED => "UAE Dirham",
                CurrencyCode.TND => "Tunisian Dinar",
                CurrencyCode.UGX => "Uganda Shilling",
                CurrencyCode.MKD => "Denar",
                CurrencyCode.EGP => "Egyptian Pound",
                CurrencyCode.GBP => "Pound Sterling",
                CurrencyCode.TZS => "Tanzanian Shilling",
                CurrencyCode.USD => "US Dollar",
                CurrencyCode.UYU => "Peso Uruguayo",
                CurrencyCode.UZS => "Uzbekistan Sum",
                CurrencyCode.WST => "Tala",
                CurrencyCode.YER => "Yemeni Rial",
                CurrencyCode.TWD => "New Taiwan Dollar",
                CurrencyCode.SLE => "Leone",
                CurrencyCode.VES => "Bolivar",
                CurrencyCode.MRU => "Ouguiya",
                CurrencyCode.STN => "Dobra",
                CurrencyCode.ZWL => "Zimbabwe Dollar",
                CurrencyCode.BYN => "Belarussian Ruble",
                CurrencyCode.TMT => "Turkmenistan New Manat",
                CurrencyCode.GHS => "Ghana Cedi",
                CurrencyCode.SDG => "Sudanese Pound",
                CurrencyCode.UYI => "Uruguay Peso",
                CurrencyCode.RSD => "Serbian Dinar",
                CurrencyCode.MZN => "Mozambique Metical",
                CurrencyCode.AZN => "Azerbaijanian Manat",
                CurrencyCode.RON => "Romanian Leu",
                CurrencyCode.TRY => "Turkish Lira",
                CurrencyCode.XAF => "Central African CFA franc",
                CurrencyCode.XCD => "East Caribbean Dollar",
                CurrencyCode.XOF => "West African CFA franc",
                CurrencyCode.XPF => "CFP Franc",
                CurrencyCode.ZMW => "Zambian Kwacha",
                CurrencyCode.SRD => "Surinam Dollar",
                CurrencyCode.MGA => "Malagasy Ariary",
                CurrencyCode.AFN => "Afghani",
                CurrencyCode.TJS => "Somoni",
                CurrencyCode.AOA => "Kwanza",
                CurrencyCode.BGN => "Bulgarian Lev",
                CurrencyCode.CDF => "Congolese Franc",
                CurrencyCode.BAM => "Convertible Mark",
                CurrencyCode.EUR => "Euro",
                CurrencyCode.UAH => "Hryvnia",
                CurrencyCode.GEL => "Lari",
                CurrencyCode.PLN => "Zloty",
                CurrencyCode.BRL => "Brazilian Real",
                _ => throw new NotSupportedException($"Missing description for currency code {currencyCode}")
            };
        }
    }
}